name: build
on:
  push:
    branches:
      - 'main'
env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  REGISTRY_USERNAME: miaojun_personal
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PWD }}
          registry: ${{ env.REGISTRY }}

      - name: Build backend and push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/mj-mirror/backend:${{ steps.vars.outputs.sha_short }}

      - name: Checkout Manifests
        uses: actions/checkout@v4
        with:
          repository: miaojuncn/gitops-manifests
          path: gitops-manifests

      - name: Update image version in related manifests
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'backend/backend.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ${{ env.REGISTRY }}/mj-mirror/backend:${{ steps.vars.outputs.sha_short }}
          repository: miaojuncn/gitops-manifests
          branch: dev
          targetBranch: main
          createPR: true
#          commitChange: true
          message: 'Update image version to ${{ steps.vars.outputs.sha_short }}'
          token: ${{ secrets.TOKEN }}
          workDir: gitops-manifests
